# Site settings
title: Patty Lowy
description: Patty is an artist in New York City, painting, drawing, and printmaking.
url: "http://pattylowy.com" # the base hostname & protocol for your site
sass:
    sass_dir: _scss
